Make Windows and Unix setup scripts consistent with each other

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,30 +1,27 @@
 #!/bin/sh
 
-# Copyright (c) 2015 Susam Pal
-# All rights reserved.
+# The MIT License (MIT)
 #
-# Redistribution and use in source and binary forms, with or without
-# modification, are permitted provided that the following conditions
-# are met:
+# Copyright (c) 2015-2016 Susam Pal
 #
-#   1. Redistributions of source code must retain the above copyright
-#      notice, this list of conditions and the following disclaimer.
-#   2. Redistributions in binary form must reproduce the above copyright
-#      notice, this list of conditions and the following disclaimer in
-#      the documentation and/or other materials provided with the
-#      distribution.
+# Permission is hereby granted, free of charge, to any person obtaining
+# a copy of this software and associated documentation files (the
+# "Software"), to deal in the Software without restriction, including
+# without limitation the rights to use, copy, modify, merge, publish,
+# distribute, sublicense, and/or sell copies of the Software, and to
+# permit persons to whom the Software is furnished to do so, subject to
+# the following conditions:
 #
-# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
-# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
-# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
-# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
-# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
-# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
-# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
-# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+# The above copyright notice and this permission notice shall be
+# included in all copies or substantial portions of the Software.
+#
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
+# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
+# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
+# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
+# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
+# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
+# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 
 
 # Files for which symbolic links need to be set up.
@@ -38,97 +35,47 @@ tmux.conf
 Xresources
 "
 
+VERSION=0.1.1
+AUTHOR="Susam Pal"
+COPYRIGHT="Copyright (c) 2015-2016 $AUTHOR"
 
-# Script version.
-VERSION=0.1.0
+LICENSE_URL="http://susam.in/licenses/mit/"
+SUPPORT_URL="https://github.com/susam/dotfiles/issues"
 
-# Script version details.
-CHANGELOG="
-0.1.0 (2015-10-11)
------------------
-  - NEW: Create symbolic links as dot-files.
+NOTICE="
+This is free and open source software. You can use, copy, modify,
+merge, publish, distribute, sublicense, and/or sell copies of it,
+under the terms of the MIT License. You can obtain a copy of the
+MIT License at <$LICENSE_URL>.
+
+This software is provided \"AS IS\", WITHOUT WARRANTY OF ANY KIND,
+express or implied. See the MIT License for details.
 "
 
-# Copyright notice.
-COPYRIGHT="Copyright (c) 2015 Susam Pal
-
-This is free software. You are permitted to redistribute and use it in
-source and binary forms, with or without modification, under the terms
-of the Simplified BSD License. See <http://susam.in/licenses/bsd/> for
-the complete license."
+NAME=${0##*/}
 
 
 # Starting point of this script.
 #
 # Arguments:
-#   "$@" -- All command line arguments specified while invoking this
-#           script must be passed to this function.
+#   arg...: All arguments this script was invoked with.
 main()
 {
     parse_arguments "$@"
 
-    if [ $delete = yes ]
+    if [ $undo = no ]
     then
-        delete_dot_files
-    else
         setup_dot_files
+    else
+        undo_dot_files
     fi
-}
-
-
-# Create symbolic links for dot-files.
-setup_dot_files()
-{
-    printf "%s" "$DOT_FILES" | grep [[:graph:]] | while read filename
-    do
-        target="$PWD/$filename"
-        link=~/."$filename"
-
-        if [ ! -f "$target" ]
-        then
-            printf "File %s does not exist\n" "$target" >&2
-        elif ln -s "$target" "$link"
-        then
-            printf "Created %s -> %s\n" "$link" "$target"
-        fi
-    done
-}
-
-
-# Delete all files created by the setup function.
-delete_dot_files()
-{
-    printf "%s" "$DOT_FILES" | grep [[:graph:]] | while read filename
-    do
-        link=~/."$filename"
-        if rm "$link"
-        then
-            printf "Deleted %s\n" "$link"
-        fi
-    done
-}
-
-
-# Terminate the script with an error message.
-#
-# Arguments:
-#   string... -- String to print to standard error stream.
-#
-# Errors:
-#   Unconditionally causs the script to terminate with an error message
-#   and exit code 1.
-quit()
-{
-    printf "%s: %s\n" "$0" "$*" >&2
-    exit 1
 }
 
 
 # Parse command line arguments passed to this script.
 #
 # Arguments:
-#   "$@" -- All command line arguments specified while invoking this
-#           script must be passed to this function.
+#   arg...: All arguments this script was invoked with.
 #
 # Errors:
 #   If invalid arguments are specified, this function causes the script
@@ -136,19 +83,15 @@ quit()
 parse_arguments()
 {
     # Default options.
-    delete=no
+    undo=no
 
     # Parse command line options.
     while [ "$#" -gt 0 ]
     do
         case $1 in
-            -d | --delete)
-                delete=yes
+            -u | --undo)
+                undo=yes
                 shift
-                ;;
-            -c | --changelog)
-                show_changelog
-                exit
                 ;;
             -h | --help)
                 show_help
@@ -169,36 +112,95 @@ parse_arguments()
 }
 
 
+# Create symbolic links for dot-files.
+setup_dot_files()
+{
+    printf "%s" "$DOT_FILES" | grep [[:graph:]] | while read filename
+    do
+        target="$PWD/$filename"
+        link=~/."$filename"
+
+        if [ -f "$link" ]
+        then
+            err Link "$link" already exists.
+        elif [ ! -f "$target" ]
+        then
+            err File "$target" does not exist.
+        elif ln -s "$target" "$link"
+        then
+            printf "Created %s -> %s\n" "$link" "$target".
+        fi
+    done
+}
+
+
+# Delete symbolic links for dot-files.
+undo_dot_files()
+{
+    printf "%s" "$DOT_FILES" | grep [[:graph:]] | while read filename
+    do
+        link=~/."$filename"
+        if [ ! -f "$link" ]
+        then
+            err Link "$link" does not exist.
+        elif rm "$link"
+        then
+            printf "Deleted %s\n" "$link".
+        fi
+    done
+}
+
+
+# Print error message.
+#
+# Arguments:
+#   string...: String to print to standard error stream.
+#
+# Errors:
+#   Unconditionally causs the script to terminate with an error message
+#   and exit code 1.
+err()
+{
+    printf "%s: %s\n" "$NAME" "$*" >&2
+}
+
+
+# Terminate the script with an error message.
+#
+# Arguments:
+#   string...: String to print to standard error stream.
+#
+# Errors:
+#   Unconditionally causes the script to terminate with an error message
+#   and exit code 1.
+quit()
+{
+    err "$*"
+    exit 1
+}
+
+
 # Show help.
 show_help()
 {
-    printf "%s\n" "Usage: $0 [-d] [-h]
+    printf "%s\n" \
+"Usage: $NAME [-u] [-h] [-v]
 
 Set up dot-files in home directory.
 
 Options:
-  -d, --delete     Delete symbolic links to dot-files.
-  -c, --changelog  Show changelog and exit.
-  -h, --help       Show this help and exit.
-  -v, --version    Show version and exit.
+  -u, --undo     Undo setup.
+  -h, --help     Show this help and exit.
+  -v, --version  Show version and exit.
 
-Report bugs to <https://github.com/susam/dotfiles/issues>."
+Report bugs to <$SUPPORT_URL>."
 }
 
 
 # Show version and copyright.
 show_version()
 {
-    printf "%s %s\n%s\n" "${0##*/}" "$VERSION" "$COPYRIGHT"
-}
-
-
-# Show changelog.
-show_changelog()
-{
-    echo Changelog
-    echo =========
-    printf %s "$CHANGELOG"
+    printf "%s %s\n%s\n" "$NAME" "$VERSION" "$COPYRIGHT"
 }
 
 
